from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as f:
    long_description = f.read()

setup(
    name="menoa",
    version="0.6.0",
    author="Jack Hagen",
    author_email="jack@example.com",
    description="Menoa Linux Security Suite",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/JackHagen/menoa",
    license="MIT",
    python_requires=">=3.11",
    packages=find_packages(include=["menoa", "menoa.*"]),
    install_requires=[
        "bidict==0.23.1",
        "certifi==2025.7.14",
        "charset-normalizer==3.4.2",
        "click==8.2.1",
        "colorama==0.4.6",
        "coloredlogs==15.0.1",
        "cvdupdate==1.1.3",
        "dbus-fast==2.44.1",
        "desktop-notifier==6.1.1",
        "dnspython==2.7.0",
        "humanfriendly==10.0",
        "idna==3.10",
        "joblib==1.5.1",
        "markdown-it-py==3.0.0",
        "mdurl==0.1.2",
        "numpy==2.3.1",
        "packaging==25.0",
        "pandas==2.3.1",
        "psutil==7.0.0",
        "Pygments==2.19.2",
        "PySide6==6.9.1",
        "PySide6_Addons==6.9.1",
        "PySide6_Essentials==6.9.1",
        "python-dateutil==2.9.0.post0",
        "pytz==2025.2",
        "rangehttpserver==1.4.0",
        "requests==2.32.4",
        "rich==14.0.0",
        "scikit-learn==1.7.1",
        "scipy==1.16.0",
        "shellingham==1.5.4",
        "shiboken6==6.9.1",
        "six==1.17.0",
        "threadpoolctl==3.6.0",
        "tomli==2.2.1",
        "tomli_w==1.2.0",
        "tqdm==4.67.1",
        "typing_extensions==4.14.1",
        "tzdata==2025.2",
        "urllib3==2.5.0"
    ],
    package_data={
        "menoa": [
            "dark_style.qss",
            "light_style.qss",
            "notification_icon.png",
            "utils/*.py",
            "pages/*.py"
        ],
    },
    include_package_data=True,
    entry_points={
        "console_scripts": [
            "menoa=menoa.cli:main",
        ],
        "gui_scripts": [
            "menoa-gui=menoa.main:main",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: System Administrators",
        "License :: OSI Approved :: MIT License",
        "Operating System :: POSIX :: Linux",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Security",
    ],
    project_urls={
        "Source": "https://github.com/JackHagen/menoa",
    },
)
